"""Add status and message to payment_logs

Revision ID: 4618ad4692a6
Revises: a25aae33d15e
Create Date: 2025-06-02 10:32:29.911094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4618ad4692a6'
down_revision: Union[str, None] = 'a25aae33d15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_logs', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('payment_logs', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_logs', 'message')
    op.drop_column('payment_logs', 'status')
    # ### end Alembic commands ###
