"""Initial migration

Revision ID: a25aae33d15e
Revises: 
Create Date: 2025-05-30 15:05:38.361980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25aae33d15e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_logs', sa.Column('currency', sa.String(length=10), nullable=False))
    op.alter_column('payment_logs', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=False)
    op.drop_column('payment_logs', 'status')
    op.drop_column('payment_logs', 'method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_logs', sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment_logs', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('payment_logs', 'amount',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('payment_logs', 'currency')
    # ### end Alembic commands ###
